"""Tambah model Wisata

Revision ID: 10af95aab5d9
Revises: 212c751425f5
Create Date: 2025-09-17 19:46:39.133323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10af95aab5d9'
down_revision = '212c751425f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wisata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('gambar_url', sa.String(length=255), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wisata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wisata_nama'), ['nama'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wisata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wisata_nama'))

    op.drop_table('wisata')
    # ### end Alembic commands ###
