"""Tambah model Review dan relasinya

Revision ID: 71a19c414ad7
Revises: b7b4bb7b06a7
Create Date: 2025-09-24 17:48:00.498905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71a19c414ad7'
down_revision = 'b7b4bb7b06a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('komentar', sa.Text(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wisata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wisata_id'], ['wisata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_tanggal_dibuat'), ['tanggal_dibuat'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_tanggal_dibuat'))

    op.drop_table('reviews')
    # ### end Alembic commands ###
