"""Tambah model Itinerari dan relasinya

Revision ID: 7dc21b2565a7
Revises: 
Create Date: 2025-09-26 13:06:13.754249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc21b2565a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('penyelenggara', sa.String(length=100), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_nama'), ['nama'], unique=False)

    op.create_table('paket_wisata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('harga', sa.Integer(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paket_wisata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paket_wisata_nama'), ['nama'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('wisata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('gambar_url', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wisata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wisata_nama'), ['nama'], unique=False)

    op.create_table('itinerari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerari', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerari_tanggal_dibuat'), ['tanggal_dibuat'], unique=False)

    op.create_table('paket_wisata_association',
    sa.Column('paket_id', sa.Integer(), nullable=False),
    sa.Column('wisata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paket_id'], ['paket_wisata.id'], ),
    sa.ForeignKeyConstraint(['wisata_id'], ['wisata.id'], ),
    sa.PrimaryKeyConstraint('paket_id', 'wisata_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('komentar', sa.Text(), nullable=False),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wisata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wisata_id'], ['wisata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_tanggal_dibuat'), ['tanggal_dibuat'], unique=False)

    op.create_table('foto_ulasan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_file', sa.String(length=100), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itinerari_wisata_association',
    sa.Column('itinerari_id', sa.Integer(), nullable=False),
    sa.Column('wisata_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerari_id'], ['itinerari.id'], ),
    sa.ForeignKeyConstraint(['wisata_id'], ['wisata.id'], ),
    sa.PrimaryKeyConstraint('itinerari_id', 'wisata_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itinerari_wisata_association')
    op.drop_table('foto_ulasan')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_tanggal_dibuat'))

    op.drop_table('reviews')
    op.drop_table('paket_wisata_association')
    with op.batch_alter_table('itinerari', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerari_tanggal_dibuat'))

    op.drop_table('itinerari')
    with op.batch_alter_table('wisata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wisata_nama'))

    op.drop_table('wisata')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('paket_wisata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paket_wisata_nama'))

    op.drop_table('paket_wisata')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_nama'))

    op.drop_table('event')
    # ### end Alembic commands ###
