"""Tambah model Event

Revision ID: b7b4bb7b06a7
Revises: 10af95aab5d9
Create Date: 2025-09-23 20:10:46.840465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b4bb7b06a7'
down_revision = '10af95aab5d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('tanggal', sa.DateTime(), nullable=False),
    sa.Column('lokasi', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('penyelenggara', sa.String(length=100), nullable=True),
    sa.Column('tanggal_dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_nama'), ['nama'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_nama'))

    op.drop_table('event')
    # ### end Alembic commands ###
